---
- name: Copy rpm
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp"
    mode: "0600"
  loop: "{{ pgroute66_local_packages }}"

- name: Local install pgroute66
  ansible.builtin.package:
    name: "/tmp/{{ item }}"
    state: "{{ pgroute66_package_state }}"
  loop: "{{ pgroute66_local_packages }}"

- name: Install pgroute66
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pgroute66_package_state }}"
  loop: "{{ pgroute66_packages }}"
